package com.example.ebaylister.ui

data class EbayListerUiState(
    val backendBaseUrl: String = "http://192.168.1.10:8000",
    val localBackendUrl: String = "http://192.168.1.10:8000",
    val cloudBackendUrl: String = "https://your-backend-url.onrender.com",
    val backendMode: String = "local",
    val backendApiToken: String = "",
    val connectionStatus: String = "Not tested",
    val visionProvider: String = "unknown",
    val visionModelName: String = "unknown",
    val normalizedKeywords: String = "",
    val compsSource: String = "",
    val photoStatus: String = "No photo captured yet",
    val capturedPhotoPath: String? = null,
    val detectedItem: String = "Tap analyze to identify an item",
    val rawDetectedItem: String = "",
    val candidateItems: List<String> = emptyList(),
    val detectedConfidence: String = "Confidence: unknown",
    val listedCount: Int = 0,
    val soldCount: Int = 0,
    val averageSoldPrice: String = "$0.00",
    val medianSoldPrice: String = "$0.00",
    val lowSoldPrice: String = "$0.00",
    val highSoldPrice: String = "$0.00",
    val ebayConnectionStatus: String = "Not connected",
    val listingDraftStatus: String = "No listing draft created",
    val statusMessage: String = "Ready to capture a photo and begin analysis.",
    val debugEnabled: Boolean = true,
    val debugLog: String = "Debug log ready.",
)
