package com.example.ebaylister.ui

data class SavedDraftItem(
    val id: String,
    val title: String,
    val medianPrice: String,
    val averagePrice: String,
    val lowPrice: String,
    val highPrice: String,
    val source: String,
    val normalizedKeywords: String,
    val suggestedKeywords: List<String>,
    val listedCount: Int,
    val soldCount: Int,
    val confidence: String,
    val listingNotes: String,
    val photoPath: String,
    val targetPrice: String,
    val draftDescription: String,
    val additionalPhotoPaths: List<String> = emptyList(),
    val publishedListingUrl: String = "",
    val condition: String = "",
    val category: String = "",
    val shippingProfile: String = "",
    val returnPolicy: String = "",
    val quantity: Int = 1,
)

data class ListingEditorState(
    val draftId: String,
    val title: String,
    val description: String,
    val price: String,
    val photoPaths: List<String>,
    val condition: String = "",
    val category: String = "",
    val shippingProfile: String = "",
    val returnPolicy: String = "",
    val quantity: Int = 1,
    val validationErrors: List<String> = emptyList(),
    val publishStatus: String = "Not published yet.",
    val publishedListingUrl: String = "",
    val isPublishing: Boolean = false,
)

data class EbayListerUiState(
    val backendBaseUrl: String = "http://127.0.0.1:8000",
    val localBackendUrl: String = "http://127.0.0.1:8000",
    val cloudBackendUrl: String = "",
    val backendMode: String = "local",
    val backendApiToken: String = "",
    val connectionStatus: String = "Not tested",
    val visionProvider: String = "unknown",
    val visionModelName: String = "unknown",
    val normalizedKeywords: String = "",
    val compsSource: String = "",
    val photoStatus: String = "No photo captured yet",
    val capturedPhotoPath: String? = null,
    val detectedItem: String = "Tap analyze to identify an item",
    val rawDetectedItem: String = "",
    val listingDescription: String = "",
    val candidateItems: List<String> = emptyList(),
    val detectedConfidence: String = "Confidence: unknown",
    val listedCount: Int = 0,
    val soldCount: Int = 0,
    val averageSoldPrice: String = "$0.00",
    val medianSoldPrice: String = "$0.00",
    val lowSoldPrice: String = "$0.00",
    val highSoldPrice: String = "$0.00",
    val ebayConnectionStatus: String = "Not connected",
    val listingDraftStatus: String = "No listing draft created",
    val isAnalyzing: Boolean = false,
    val savedDrafts: List<SavedDraftItem> = emptyList(),
    val listingEditor: ListingEditorState? = null,
    val statusMessage: String = "Local USB backend is prefilled for testing. API token is optional unless backend auth is enabled.",
    val debugEnabled: Boolean = true,
    val debugLog: String = "Debug log ready.",
)
